language: cpp
compiler:
  - clang
  - gcc

env:
  matrix:
    - FGT_WITH_OPENMP=ON OMP_NUM_THREADS=4
    - FGT_WITH_OPENMP=OFF
  global:
    secure: ZN/AGl23+zH+afTiBq6CMelSaZYK3dCk2a4Y9hPYYCOXOMCDXo/s8jtQxUdwCTjChBsdRgTnZCXeMgGEbK7aH75Kw1pEeOcT/n2yHgY75ZJH6R2U+DPCkX5A+WHdzHBP+N0IouAOieYP+nMNqc7yEvzAi1vJ50X0sSGiFdNzASo=

matrix:
  exclude:
    - compiler: clang
      env: FGT_WITH_OPENMP=ON OMP_NUM_THREADS=4

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8

install:
  - scripts/travis-install-cmake.sh && export PATH=$(pwd)/cmake-3.0.2/bin:$PATH
  - scripts/travis-install-eigen3.sh

before_script:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi

script:
  - scripts/travis-script.sh

after_success: scripts/gh-pages.sh
