language: cpp

compiler:
    - clang
    - gcc

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - kalakris-cmake
        packages:
            - g++-4.8
            - cmake
            - cmake-data
            - libgomp1

env:
    - FGT_WITH_OPENMP=ON OMP_NUM_THREADS=4
    - FGT_WITH_OPENMP=OFF

matrix:
    exclude:
        - compiler: clang
          env: FGT_WITH_OPENMP=ON OMP_NUM_THREADS=4

install:
    - bash scripts/install-armadillo.sh $HOME/armadillo

cache:
    directories:
        - $HOME/armadillo

before_script:
    - if [[ $CXX == "g++" ]]; then
      export CXX="g++-4.8";
      fi

script:
    - mkdir build && cd build && cmake .. -BUILD_TESTS=ON -DWITH_OPENMP=$FGT_WITH_OPENMP -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$HOME/fgt && make
    - build/bin/fgt-test
    - build/bin/fgt-trial
    - cd build && make install
